version: '3.8'
services:
    pokedex-api:
        container_name: pokedexapi-db
        image: postgres:12.5-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: pokedexapi-db