server:
  servlet:

    context-path: /buscaCep

  port: 8081

cep-external-api:

spring:
  datasource:
    driverClassName: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/addressApi-db

    username: postgres
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
