server:
  port: 8081
  servlet:
      context-path: /addressapi

cep-external-api:
app:
  cep:
    api: BRASILAPI
    fallback-order: VIACEP,CEPABERTO,BRASILAPI
    fallback: true

spring:
  datasource:
    driverClassName: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/addressapidb

    username: postgres
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
